<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.9.6 on win32)" generated="20231205 22:59:22.496" rpa="false" schemaversion="4">
<suite id="s1" name="Bookflight" source="c:\Users\Leni Andriani\Desktop\Sanbercode51-Mobile\suites\bookflight.robot">
<test id="s1-t1" name="Open and login Flight Application" line="10">
<kw name="Open Flight Application" library="base">
<kw name="Open Application" library="AppiumLibrary">
<arg>remote_url=${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<msg timestamp="20231205 22:59:25.167" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87190&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 22:59:27.199" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87310&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 22:59:29.245" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87E20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20231205 22:59:31.286" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20231205 22:59:31.283" endtime="20231205 22:59:31.318"/>
</kw>
<msg timestamp="20231205 22:59:31.327" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20231205 22:59:31.331" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB874F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20231205 22:59:23.089" endtime="20231205 22:59:31.336"/>
</kw>
<status status="FAIL" starttime="20231205 22:59:23.088" endtime="20231205 22:59:31.337"/>
</kw>
<kw name="Click Sign In Button On Home Screen" library="homePage">
<status status="NOT RUN" starttime="20231205 22:59:31.340" endtime="20231205 22:59:31.340"/>
</kw>
<kw name="Input Username On Login Page" library="loginPage">
<arg>${valid-username}</arg>
<status status="NOT RUN" starttime="20231205 22:59:31.342" endtime="20231205 22:59:31.343"/>
</kw>
<kw name="Input Password On Login Page" library="loginPage">
<arg>${valid-password}</arg>
<status status="NOT RUN" starttime="20231205 22:59:31.344" endtime="20231205 22:59:31.345"/>
</kw>
<kw name="Click Button Sign In On Login page" library="bookflight">
<status status="NOT RUN" starttime="20231205 22:59:31.347" endtime="20231205 22:59:31.347"/>
</kw>
<status status="FAIL" starttime="20231205 22:59:23.086" endtime="20231205 22:59:31.350">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB874F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20231205 22:59:22.510" endtime="20231205 22:59:31.358"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Bookflight">Bookflight</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231205 22:59:25.167" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87190&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 22:59:27.199" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87310&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 22:59:29.245" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001EB1CB87E20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 22:59:31.327" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
