<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.9.6 on win32)" generated="20231205 21:21:20.463" rpa="false" schemaversion="4">
<suite id="s1" name="Bookflight" source="c:\Users\Leni Andriani\Desktop\Sanbercode51-Mobile\suites\bookflight.robot">
<test id="s1-t1" name="Open and login Flight Application" line="10">
<kw name="Open Flight Application" library="Base">
<kw name="Open Application" library="AppiumLibrary">
<arg>remote_url=${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion =${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<msg timestamp="20231205 21:21:23.292" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C181557C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 21:21:25.350" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 21:21:27.384" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188E80&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20231205 21:21:29.429" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20231205 21:21:29.427" endtime="20231205 21:21:29.705"/>
</kw>
<msg timestamp="20231205 21:21:29.714" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20231205 21:21:29.717" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188D00&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20231205 21:21:21.182" endtime="20231205 21:21:29.724"/>
</kw>
<status status="FAIL" starttime="20231205 21:21:21.181" endtime="20231205 21:21:29.725"/>
</kw>
<kw name="Click Sign In Button On Home Screen">
<status status="NOT RUN" starttime="20231205 21:21:29.736" endtime="20231205 21:21:29.737"/>
</kw>
<kw name="Input Username On Login Page" library="loginPage">
<arg>${valid-username}</arg>
<status status="NOT RUN" starttime="20231205 21:21:29.741" endtime="20231205 21:21:29.742"/>
</kw>
<kw name="Input Password On Login Page" library="loginPage">
<arg>${valid-password}</arg>
<status status="NOT RUN" starttime="20231205 21:21:29.744" endtime="20231205 21:21:29.744"/>
</kw>
<kw name="Click Button Sign In On Login page" library="bookflight">
<status status="NOT RUN" starttime="20231205 21:21:29.747" endtime="20231205 21:21:29.748"/>
</kw>
<status status="FAIL" starttime="20231205 21:21:21.179" endtime="20231205 21:21:29.750">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188D00&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20231205 21:21:20.496" endtime="20231205 21:21:29.756"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Bookflight">Bookflight</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231205 21:21:23.292" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C181557C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 21:21:25.350" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188490&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 21:21:27.384" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000023C18188E80&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20231205 21:21:29.714" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
